// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyADx3Gyd3iPJipALJkfPnGsSu_-bKI5rWw',
    appId: '1:272850360399:web:8c490abd24eb393fe7723a',
    messagingSenderId: '272850360399',
    projectId: 'inteligence-companya',
    authDomain: 'inteligence-companya.firebaseapp.com',
    storageBucket: 'inteligence-companya.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA3onKbB3TdQC9zFkwt-bausB5Cevns9rw',
    appId: '1:272850360399:android:01c66a576f7158cde7723a',
    messagingSenderId: '272850360399',
    projectId: 'inteligence-companya',
    storageBucket: 'inteligence-companya.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB2Co_7FsjyxZ2HAEwKnko9JB5GA920ejE',
    appId: '1:272850360399:ios:e18a5e8a38220945e7723a',
    messagingSenderId: '272850360399',
    projectId: 'inteligence-companya',
    storageBucket: 'inteligence-companya.firebasestorage.app',
    iosBundleId: 'com.example.intelligenceCompanyIa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2Co_7FsjyxZ2HAEwKnko9JB5GA920ejE',
    appId: '1:272850360399:ios:e18a5e8a38220945e7723a',
    messagingSenderId: '272850360399',
    projectId: 'inteligence-companya',
    storageBucket: 'inteligence-companya.firebasestorage.app',
    iosBundleId: 'com.example.intelligenceCompanyIa',
  );
}
